FROM php:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y apache2


RUN docker-php-ext-install pdo pdo_mysql


RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

COPY ./configs/back/apache.conf /etc/apache2/sites-available/


CMD ["apachectl","-D","FOREGROUND"]

RUN echo 'ServerName  127.0.0.1' >> /etc/apache2/apache2.conf
RUN a2ensite apache

RUN a2enmod expires
RUN a2enmod rewrite

EXPOSE 80
EXPOSE 443