FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y apache2
RUN apt-get install -y php
RUN apt-get install -y php-dev
RUN apt-get install -y php-mysql
RUN apt-get install -y libapache2-mod-php
RUN apt-get install -y php-curl
RUN apt-get install -y php-json
RUN apt-get install -y php-common
RUN apt-get install -y php-mbstring
RUN apt-get install -y composer
RUN apt-get install -y php-xdebug
RUN curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | /bin/bash


RUN pecl install xdebug

RUN echo "xdebug.mode=debug" >> /etc/php/8.1/apache2/conf.d/20-xdebug-local.ini \
        && echo "xdebug.client_host = 172.17.0.1" >> \
    /etc/php/8.1/apache2/conf.d/20-xdebug-local.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY ./configs/back/apache.conf /etc/apache2/sites-available/


CMD ["apachectl","-D","FOREGROUND"]

RUN echo 'ServerName  127.0.0.1' >> /etc/apache2/apache2.conf
RUN a2ensite apache

RUN a2enmod expires
RUN a2enmod rewrite

EXPOSE 80
EXPOSE 443