version: "3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    build:
      dockerfile: Dockerfile_nginx
      context: .
    ports:
      - "80:80"
  backend:
    container_name: backend_app
    build:
        dockerfile: Dockerfile_back
        context: .
    ports:
      - "8080:8080"
    volumes:
      - ./Basketball-back:/var/www/html
      - ./php.ini:/usr/local/etc/php/8.1/apache2/conf.d/20-xdebug-local.ini

  frontend:
    container_name: frontend_app
    build:
      dockerfile: Dockerfile_front
      context: .
    ports:
      - "3000:3000"


