FROM node:16-alpine as build
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY ./Basketball-front/package.json ./
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install
COPY ./Basketball-front .
# Build the app
RUN npm run build

# Bundle static assets with nginx
FROM nginx:1.21.0-alpine
COPY configs/front/nginx.conf /etc/nginx/conf.d/default.conf
# Copy built assets from `builder` image
COPY --from=build /app /usr/share/nginx/html
# Add your apache.conf
# Expose port
# Start nginx
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 3000
#EXPOSE 3000
