version: "3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: ./Basketball-front
      context: ./Basketball-front
    ports:
      - "3000:80"
  backend:
    container_name: backend_app
    build: ./Basketball-back
    ports:
      - "80:80"
    volumes:
      - /app/node_modules

  frontend:
    container_name: frontend_app
    build:
      dockerfile:  ./Basketball-front/
    ports:
      - "80:3000"
      - "3000:3000"
    volumes:
      - /app/node_modules