version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"

  API:
    image: basketball_back
    build: .
    ports:
      - "8080:8080"
    volumes:
        - ./:/var/www/html
    depends_on:
      - nginx

  frontend:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - nginx
    networks:
      - frontend

  # Networks to be created to facilitate communication between containers
networks:
  API:
  frontend: